todolist/app_todo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.task_list, name='task_list'),
    path('create/', views.task_create, name='task_create'),
    path('update/<int:pk>/', views.task_update, name='task_update'),
    path('delete/<int:pk>/', views.task_delete, name='task_delete'),
    path('<int:pk>/complete/', views.task_complete, name='task_complete'),
    path('<int:pk>/uncomplete/', views.task_uncomplete, name='task_uncomplete'),

]

todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_todo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/app_todo/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(blank=True , max_length=200)
    completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(default=timezone.now)
    due_date = models.DateField(blank=True , null=True)
    attachment = models.FileField(upload_to='attachments/' , blank=True , null=True)
    
    def __str__(self):
        return self.title

todolist/app_todo/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    due_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=False
    )
    attachment = forms.FileField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Task
        fields = ['title', 'description', 'completed', 'due_date', 'attachment']

todolist/app_todo/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, get_object_or_404
from .models import Task
from .forms import TaskForm

from django.utils import timezone

from django.utils import timezone

def task_list(request):
    
    search_query = request.GET.get('search', '')
    order_mode = request.GET.get('order', '')
    
    
    print(f"search_query: {search_query}, order_mode: {order_mode}")
    tasks = Task.objects.all()
    
    tasks = Task.objects.all()
    if search_query:
        tasks = tasks.filter(title__icontains=search_query)
    if order_mode == "completed":
        tasks = tasks.order_by('-completed', '-created_date')
    elif order_mode == "not_completed":
        tasks = tasks.order_by('completed', '-created_date')
    else:
        tasks = tasks.order_by('-created_date')  # فقط یک بار این خط
    
    today = timezone.now().date()
    today_tasks = Task.objects.filter(created_date__date=today)
    completed_today = today_tasks.filter(completed=True).count()
    uncompleted_today = today_tasks.filter(completed=False).count()
    all_today = today_tasks.count()
    percent_today = int((completed_today / all_today) * 100) if all_today > 0 else 0

    context = {
        'tasks': tasks,
        'today_completed': completed_today,
        'today_uncompleted': uncompleted_today,
        'today_total': all_today,
        'percent_today': percent_today,
        'show_dashboard': True,
    }
    return render(request, 'app_todo/task_list.html', context)


def task_create(request):
    if request.method == 'POST':
        form = TaskForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm()
    return render(request, 'app_todo/task_form.html', {'form': form})


def task_update(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm(instance=task)
    return render(request, 'app_todo/task_form.html', {'form': form})

def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    from django.utils import timezone
    today = timezone.now().date()
    today_tasks = Task.objects.filter(created_date__date=today)
    completed_today = today_tasks.filter(completed=True).count()
    uncompleted_today = today_tasks.filter(completed=False).count()
    all_today = today_tasks.count()
    percent_today = int((completed_today / all_today) * 100) if all_today > 0 else 0

    if request.method == 'POST':
        task.delete()
        return redirect('task_list')
    return render(request, 'app_todo/task_confirm_delete.html', {
        'task': task,
        'today_completed': completed_today,
        'today_uncompleted': uncompleted_today,
        'today_total': all_today,
        'percent_today': percent_today,
    })



def task_complete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.completed = True
    task.save()
    return redirect('task_list')

def task_uncomplete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.completed = False
    task.save()
    return redirect('task_list')

todolist/app_todo/templates/app_todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa">
<head>


    <meta charset="UTF-8">
    <title>{% block title %}تودولیست{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <style>
        body {
            background: #f8f9fa !important;
            min-height: 100vh;
            margin: 0;
            padding: 0;
            font-family: Tahoma, Geneva, Verdana, sans-serif;
        }
    </style>
</head>
<body>

    <div style="min-height: 100vh; display: flex; flex-direction: row; justify-content: center; align-items: flex-start; padding: 20px;">
        {% if show_dashboard %}
            <div style="min-width:320px; margin-right: 28px;">
                {% include 'app_todo/dashboard_sidebar.html' %}
            </div>
        {% endif %}
        <div style="flex:1; display: flex; justify-content: center; align-items: center;">
            <div style="width: 100%; max-width: 900px;">
            <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
              <div class="container-fluid">
                <a class="navbar-brand" href="#">ToDoList</a>
                <div class="d-flex align-items-center">
                    <button type="button" id="darkModeToggle" class="btn btn-outline-dark">حالت شب/روز</button>
                </div>
              </div>
            </nav>
                <script src="{% static 'js/darkmode.js' %}"></script>


                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>
    <link rel="stylesheet" href="{% static 'css/darkmode.css' %}">

todolist/app_todo/templates/app_todo/dashboard_sidebar.html
{% load static %}

<div class="card shadow-sm p-5 rounded bg-white mt-4" style="max-width:400px;width:100%;">
    <h4 class="text-center" style="color:#23478e;">پیشرفت امروز</h4>
    {% if today_total > 0 %}
        <div class="my-3 text-center" style="font-size:18px;color:#14a44d;">
            {{ today_completed }} از {{ today_total }} کار امروز انجام شد!
        </div>
        <canvas id="todopie" style="max-width:220px; margin:auto;"></canvas>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
            const ctx = document.getElementById('todopie').getContext('2d');
            new Chart(ctx, {
                type: 'doughnut',
                data: {
                    labels: ['انجام شده', 'انجام نشده'],
                    datasets: [{
                        data: [{{ today_completed }}, {{ today_uncompleted }}],
                        backgroundColor: ['#28a745','#dc3545'],
                        borderWidth: 3,
                    }]
                },
                options: {
                    plugins: {
                        legend: { display: true, position: 'bottom' }
                    }
                }
            });
        </script>
        <div class="text-center mt-3">
            <span class="text-success mx-2">انجام شده: {{ today_completed }}</span>
            <span class="text-danger mx-2">انجام نشده: {{ today_uncompleted }}</span>
            <span class="mx-2 text-secondary">کل: {{ today_total }}</span>
        </div>
        <div class="mt-2 text-center text-primary fw-bold">درصد انجام: {{ percent_today }}%</div>
    {% else %}
        <div class="text-center text-muted py-4">امروز هیچ کاری ثبت نشده</div>
    {% endif %}
</div>
<script src="{% static 'js/darkmode.js' %}"></script>

todolist/app_todo/templates/app_todo/task_confirm_delete.html
{% extends 'app_todo/base.html' %}
{% load static %}
{% include 'app_todo/dashboard_sidebar.html' %}


<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">



{% block title %}حذف کار{% endblock %}
{% block content %}
<script src="{% static 'js/darkmode.js' %}"></script>
    <div class="card p-4 shadow" style="max-width:420px;margin:auto;">
        <h2 class="mb-4 text-center text-danger">حذف کار</h2>
        <p class="text-center">آیا مطمئن هستید که می‌خواهید کار "<span class="fw-bold">{{ task.title }}</span>" را حذف کنید؟</p>
        <form method="post" class="d-flex justify-content-between">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger px-4">حذف</button>
            <a href="{% url 'task_list' %}" class="btn btn-secondary">انصراف</a>
        </form>
    </div>
{% endblock %}

todolist/app_todo/templates/app_todo/task_form.html
{% extends 'app_todo/base.html' %}
{% load widget_tweaks %}

{% include 'app_todo/dashboard_sidebar.html' %}
{% load static %}

{% block title %}افزودن/ویرایش کار{% endblock %}

{% block content %}
<style>
    body, html {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
    }
    .task-form-label {
        font-weight: bold;
        color: #5452d7;
        margin-bottom: 8px;
    }
    .card-custom {
        min-width:340px;
        max-width:420px;
        background: linear-gradient(135deg, #ece9ff 0%, #e7ffee 100%);
        border: none;
        box-shadow: 0 4px 16px rgba(84, 82, 215, 0.12);
    }
    .form-control:focus {
        border-color: #45c292;
        box-shadow: 0 2px 8px #45c29233;
    }
    .btn-custom {
        border:none;
        box-shadow: 0 2px 8px #5452d744;
    }
</style>


<div style="min-height:100vh;display:flex;align-items:center;justify-content:center;">
    <div class="card rounded-4 p-4 card-custom">
        <h2 class="mb-4 text-center" style="color:#5452d7;">افزودن / ویرایش کار</h2>
        <form method="post" enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            <div class="mb-3">
                <label for="id_title" class="task-form-label">عنوان کار</label>
                {{ form.title|add_class:"form-control rounded shadow-sm" }}
            </div>
            <div class="mb-3">
                <label for="id_description" class="task-form-label">توضیحات</label>
                {{ form.description|add_class:"form-control rounded shadow-sm" }}
            </div>
            <div class="mb-3">
                <label for="id_completed" class="task-form-label">انجام شده؟</label>
                <div class="form-check ms-2">
                    {{ form.completed|add_class:"form-check-input" }}
                </div>
            </div>
            <div class="mb-3">
                <label for="id_due_date" class="task-form-label">تاریخ سررسید</label>
                {{ form.due_date|add_class:"form-control rounded shadow-sm" }}
            </div>
            <div class="mb-3">
                <label for="id_attachment" class="task-form-label">
                    ضمیمه فایل
                    <i class="bi bi-paperclip"></i>
                </label>
                {{ form.attachment|add_class:"form-control" }}
            </div>
            <div class="d-flex justify-content-between mt-3">
                <button type="submit" class="btn btn-success px-4 rounded-3 btn-custom" style="background: #45c292;">ثبت</button>
                <a href="{% url 'task_list' %}" class="btn btn-secondary px-4 rounded-3 btn-custom" style="background: #5452d7; color: #fff;">بازگشت</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}
<script src="{% static 'js/darkmode.js' %}"></script>

todolist/app_todo/templates/app_todo/task_list.html
{% extends 'app_todo/base.html' %}

{% include 'app_todo/dashboard_sidebar.html' %}
{% load static %}

{% block title %}لیست کارها{% endblock %}

{% block content %}
<script src="{% static 'js/darkmode.js' %}"></script>

    <!-- فرم سرچ و فیلتر -->
    <form method="get" class="d-flex flex-wrap align-items-center justify-content-center mb-4 gap-2">
        <input type="text" name="search" class="form-control w-50 rounded shadow-sm" placeholder="جستجو عنوان" value="{{ request.GET.search }}">
        <select name="order" class="form-select w-30 rounded shadow-sm">
            <option value="">ترتیب پیش‌فرض</option>
            <option value="completed">انجام‌شده اول</option>
            <option value="not_completed">انجام‌نشده اول</option>
        </select>
        <button class="btn btn-info w-50 rounded-pill" type="submit">اعمال</button>
    </form>

    <h1 class="mb-4 text-center">لیست کارها</h1>
    <a href="{% url 'task_create' %}" class="btn btn-primary mb-3 mx-auto d-block shadow" style="width:180px;">افزودن کار جدید</a>
    <ul class="list-group w-75 mx-auto text-center">
        {% for task in tasks %}
            <li class="list-group-item py-3">
                <div class="d-flex justify-content-between align-items-center">
                    <span class="fw-bold">{{ task.title }}</span>
                    <div>
                        <a href="{% url 'task_update' task.id %}" class="btn btn-warning btn-sm mx-1 rounded-pill shadow-sm">ویرایش</a>
                        <a href="{% url 'task_delete' task.id %}" class="btn btn-danger btn-sm mx-1 rounded-pill shadow-sm">حذف</a>
                    </div>
                </div>
                <!-- اگر فایل ضمیمه وجود دارد -->
                {% if task.attachment %}
                    <a href="{{ task.attachment.url }}" target="_blank" class="btn btn-info btn-sm mt-2 rounded-pill shadow-sm">
                        <i class="bi bi-paperclip"></i> دانلود فایل
                    </a>
                {% endif %}
            </li>
        {% empty %}
            <li class="list-group-item">هیچ دیتایی ثبت نشده.</li>
        {% endfor %}
    </ul>

{% endblock %}